version: '3.9'

services:
  db:
    image: mongo:7-jammy
    hostname: db
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network: